/* tslint:disable */
/* eslint-disable */
/**
 * Lingq.com API
 * HTTP API for lingq.com
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues, getByKey } from '../runtime';
/**
 *
 * @export
 * @interface CardsHint
 */
export interface CardsHint {
  /**
   *
   * @type {number}
   * @memberof CardsHint
   */
  id: number;
  /**
   *
   * @type {boolean}
   * @memberof CardsHint
   */
  flagged: boolean;
  /**
   *
   * @type {string}
   * @memberof CardsHint
   */
  locale: string;
  /**
   *
   * @type {number}
   * @memberof CardsHint
   */
  termId: number;
  /**
   *
   * @type {boolean}
   * @memberof CardsHint
   */
  isGoogleTranslate: boolean;
  /**
   *
   * @type {number}
   * @memberof CardsHint
   */
  popularity: number;
  /**
   *
   * @type {boolean}
   * @memberof CardsHint
   */
  approved: boolean;
  /**
   *
   * @type {string}
   * @memberof CardsHint
   */
  detectedLocale: string | null;
  /**
   *
   * @type {number}
   * @memberof CardsHint
   */
  creatorId: number | null;
  /**
   *
   * @type {string}
   * @memberof CardsHint
   */
  text: string;
  /**
   *
   * @type {number}
   * @memberof CardsHint
   */
  wordId: number;
}

export function CardsHintFromJSON(json: any): CardsHint {
  return CardsHintFromJSONTyped(json, false);
}

export function CardsHintFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardsHint {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: getByKey('CardsHint', json, 'id', true, false),
    flagged: getByKey('CardsHint', json, 'flagged', true, false),
    locale: getByKey('CardsHint', json, 'locale', true, false),
    termId: getByKey('CardsHint', json, 'term_id', true, false),
    isGoogleTranslate: getByKey('CardsHint', json, 'is_google_translate', true, false),
    popularity: getByKey('CardsHint', json, 'popularity', true, false),
    approved: getByKey('CardsHint', json, 'approved', true, false),
    detectedLocale: getByKey('CardsHint', json, 'detected_locale', true, true),
    creatorId: getByKey('CardsHint', json, 'creator_id', true, true),
    text: getByKey('CardsHint', json, 'text', true, false),
    wordId: getByKey('CardsHint', json, 'word_id', true, false),
  };
}

export function CardsHintToJSON(value?: CardsHint | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    flagged: value.flagged,
    locale: value.locale,
    term_id: value.termId,
    is_google_translate: value.isGoogleTranslate,
    popularity: value.popularity,
    approved: value.approved,
    detected_locale: value.detectedLocale,
    creator_id: value.creatorId,
    text: value.text,
    word_id: value.wordId,
  };
}
