/* tslint:disable */
/* eslint-disable */
/**
 * Lingq.com API
 * HTTP API for lingq.com
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LessonTeaser,
    LessonTeaserFromJSON,
    LessonTeaserFromJSONTyped,
    LessonTeaserToJSON,
} from './';

/**
 * 
 * @export
 * @interface CollectionAllOf
 */
export interface CollectionAllOf {
    /**
     * 
     * @type {Array<LessonTeaser>}
     * @memberof CollectionAllOf
     */
    lessons: Array<LessonTeaser>;
}

export function CollectionAllOfFromJSON(json: any): CollectionAllOf {
    return CollectionAllOfFromJSONTyped(json, false);
}

export function CollectionAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lessons': ((json['lessons'] as Array<any>).map(LessonTeaserFromJSON)),
    };
}

export function CollectionAllOfToJSON(value?: CollectionAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lessons': ((value.lessons as Array<any>).map(LessonTeaserToJSON)),
    };
}

