/* tslint:disable */
/* eslint-disable */
/**
 * Lingq.com API
 * HTTP API for lingq.com
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    indexInSentence: number;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    wordId: number;
}

export function TokenFromJSON(json: any): Token {
    return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'index': json['index'],
        'text': json['text'],
        'indexInSentence': json['indexInSentence'],
        'wordId': json['wordId'],
    };
}

export function TokenToJSON(value?: Token | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'index': value.index,
        'text': value.text,
        'indexInSentence': value.indexInSentence,
        'wordId': value.wordId,
    };
}

