/* tslint:disable */
/* eslint-disable */
/**
 * Lingq.com API
 * HTTP API for lingq.com
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordHint
 */
export interface WordHint {
    /**
     * 
     * @type {number}
     * @memberof WordHint
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof WordHint
     */
    locale: string;
    /**
     * 
     * @type {boolean}
     * @memberof WordHint
     */
    flagged: boolean;
    /**
     * 
     * @type {string}
     * @memberof WordHint
     */
    text: string;
    /**
     * 
     * @type {boolean}
     * @memberof WordHint
     */
    isGoogleTranslate: boolean;
    /**
     * 
     * @type {number}
     * @memberof WordHint
     */
    popularity: number;
}

export function WordHintFromJSON(json: any): WordHint {
    return WordHintFromJSONTyped(json, false);
}

export function WordHintFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordHint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'locale': json['locale'],
        'flagged': json['flagged'],
        'text': json['text'],
        'isGoogleTranslate': json['is_google_translate'],
        'popularity': json['popularity'],
    };
}

export function WordHintToJSON(value?: WordHint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'locale': value.locale,
        'flagged': value.flagged,
        'text': value.text,
        'is_google_translate': value.isGoogleTranslate,
        'popularity': value.popularity,
    };
}

